### ISSUE TITLE
The Big Aggregation Metatask

### ISSUE THREAD

**Issue by szarnyasg** [FTSRG/ingraph#135]
* [ ] Theory
  * [ ] Discuss aggregation semantics #127 
* [x] Larger refactoring tasks
  * [x] Aggregation operations should not be performed by the Projection operator #132
  * [x] Results of aggregations should be mapped #123
* [x] Smaller traceability/cosmetic changes
  * [x] Projection arguments in the elements list not serialized #130
  * [x] Refactor the Inferencer for handling Projections and Grouping #109

**Comment by szarnyasg** [comment]
Aggregations now work quite well (as confirmed by the LDBC tests), so closing the metatask. Follow the rest of the development in #127.
