### ISSUE TITLE
engine: Incremental evaluation of standard Cypher constructions

### ISSUE THREAD

**Issue by szarnyasg** [FTSRG/ingraph#51]
(Related ticket: #35)

Use this issue to keep track of supported Cypher constructs.

### Clauses

* [x] _Query constructs_
  * [x] `MATCH`
    * [x] Transitive closure
  * [x] `RETURN` (Production node)
  * [x] `UNWIND`
  * [x] `OPTIONAL MATCH` (left outer join)
  * [x] ~`WITH`~ this is translated to joins in the query plan
  * [x] `UNION`
* [ ] _Data manipulation_ (moved to #170)
  * [x] `CREATE`
  * [ ] `MERGE`
  * [ ] `SET`
  * [ ] `DELETE`
  * [ ] `DETACH DELETE`
  * [ ] `REMOVE`
* [x] _~~Procedure calls~~_
  * [x] ~~`CALL ... YIELD`~~ (as this call may run an arbitrary Java code, there is no way we can handle these incrementally)

### Sub-clauses

* [x] _Conditions_
  * [x] `WHERE` https://github.com/FTSRG/ingraph/issues/43
* [x] _Ordering_
  * [x] `ORDER BY`
  * [x] `SKIP`
  * [x] `LIMIT`
* [ ] _Data manipulation_ (moved to #170)
  * [ ] `ON CREATE`
  * [ ] `ON MATCH`

### Operators

* [x] `DISTINCT`
* [x] String operations
  * [x] `STARTS WITH`
  * [x] `CONTAINS`
  * [x] `ENDS WITH`
* [x] ~Arithmetic comparison~ https://github.com/FTSRG/ingraph/issues/43
  * [x] ~`=`~
  * [x] ~`<>`~
  * [x] ~`<`~
  * [x] ~`>`~
  * [x] ~`<=`~
  * [x] ~`>=`~
* [x] Arithmetic operators
  * [x] `+`
  * [x] `-`
  * [x] `/`
  * [x] `*`
  * [x] `^`
  * [x] `%`
* [x] ~Logical operators~ https://github.com/FTSRG/ingraph/tree/master/queries/ldbc-snb
  * [x] ~`NOT`~
  * [x] ~`AND`~
  * [x] ~`OR`~
  * [x] ~`XOR`~
* [x] NULLs
  * [x] `IS NULL`
  * [x] `IS NOT NULL`
* [x] Accessors
  * [x] ~`.` (property access)~ not required as the query plan will be translated to tuples
  * [x] `[]` (subscript)

### Expressions

* [ ] [List comprehensions](https://neo4j.com/docs/developer-manual/3.0/cypher/#_list_comprehension) (moved to #171)
* [ ] [Pattern comprehensions](https://github.com/neo4j/neo4j/commit/c067fd918c23aebb156f4cec268e134b1f61c08e#diff-726176c1183002e63d5bb9361f5e1c52R114) (moved to #172)
* [ ] Parameters with new syntax (`$`) (moved to #85)
* [x] ~Literals~ they are just constants
* [x] [Aggregation functions](https://neo4j.com/docs/developer-manual/3.0/cypher/#query-clause)
  * [x] [`avg()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#aggregation-avg)
  * [x] [`count()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#_count)
  * [x] [`max()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#aggregation-max)
  * [x] [`min()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#aggregation-min)
  * [x] [`sum()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#aggregation-sum)
  * [x] [`collect()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#aggregation-collect)

### Functions

* [ ] [Statistical functions](https://neo4j.com/docs/developer-manual/3.0/cypher/#_statistics)
  * [ ] [`stdDev()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#aggregation-stdev)
  * [ ] [`stdDevP()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#aggregation-stdevp)
  * [ ] [`percentileCont()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#aggregation-percentilecont)
  * [ ] [`percentileDisc()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#aggregation-percentiledisc)
* [ ] [Predicate functions](https://neo4j.com/docs/developer-manual/3.0/cypher/#query-predicates)
  * [ ] [`exists()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-exists) (moved to #174)
* [ ] [Scalar functions](https://neo4j.com/docs/developer-manual/3.0/cypher/#query-functions-scalar)
  * [x] [`toFloat()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-tofloat)
  * [x] [`head()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-head)
  * [x] [`length()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-length)
  * [x] [`last()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-last)
  * [x] [`size()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-size)
  * [x] [`coalesce()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-coalesce)
  * [ ] [`startNode()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-startnode) (moved to #175)
  * [ ] [`endNode()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-endnode) (moved to #175)
  * [ ] [`properties()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-properties), (see #53)
  * [ ] [`type()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-type) (see #53)
* [ ] [List functions](https://neo4j.com/docs/developer-manual/3.0/cypher/#query-functions-list)
  * [x] [`tail()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-tail)
  * [x] [`range()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-range)
  * [ ] [`keys()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-keys) (see #53)
  * [ ] [`labels()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-labels) (see #53)
  * [ ] [`relationships()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-relationships) (moved to #175)
  * [ ] [`nodes()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-nodes) (moved to #175)
* [x] [Numeric functions](https://neo4j.com/docs/developer-manual/3.0/cypher/#query-functions-numeric)
  * [x] [`abs()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-abs)
  * [x] [`ceil()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-ceil)
  * [x] [`floor()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-floor)
  * [x] [`rand()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-rand)
  * [x] [`round()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-round)
  * [x] [`sign()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-sign)
* [x] [Logarithmic functions](https://neo4j.com/docs/developer-manual/3.0/cypher/#query-functions-logarithmic)
  * [x] [`e()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-e)
  * [x] [`exp()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-e)
  * [x] [`log()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-log)
  * [x] [`log10()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-log10)
  * [x] [`sqrt()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-sqrt)
* [x] [Trigonometric functions](https://neo4j.com/docs/developer-manual/3.0/cypher/#query-functions-trigonometric)
  * [x] [`acos()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-acos)
  * [x] [`asin()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-asin)
  * [x] [`atan()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-asin)
  * [x] [`atan2()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-atan2)
  * [x] [`cos()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-cos)
  * [x] [`cot()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-cot)
  * [x] [`degrees()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-degrees)
  * [x] [`pi()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-pi)
  * [x] [`radians()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-radians)
  * [x] [`sin()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-sin)
  * [x] [`tan()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-tan)
* [x] [String functions](https://neo4j.com/docs/developer-manual/3.0/cypher/#query-functions-string)
  * [x] [`left()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-left)
  * [x] [`right()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-right)
  * [x] [`trim()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-trim)
  * [x] [`lTrim()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-ltrim)
  * [x] [`rTrim()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-rtrim)
  * [x] [`replace()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-replace)
  * [x] [`reverse()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-reverse)
  * [x] [`split()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-split)
  * [x] [`substring()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-substring)
  * [x] [`toString()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-tostring)
  * [x] `toLower()` ([`lower()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-lower))
  * [x] `toUpper()` ([`upper()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-upper))
* [x] Not included in Cypher:
  * [x] `toBoolean()`
  * [x] `toInteger()` (called [`toInt()`](https://neo4j.com/docs/developer-manual/3.0/cypher/#functions-toint))

### Types

* [x] primitives
* [x] list
* [ ] map
* [ ] node
* [ ] relationship
* [ ] path

**Comment by szarnyasg** [comment]
Extracted this to other issues. Types will be added along the way (if required by a particular function/feature).
