### ISSUE TITLE
Roadmap for 2017 Q2

### ISSUE THREAD

**Issue by szarnyasg** [FTSRG/ingraph#66]
* [x] Decide data model #63
* [x] Implement driver #65 (@szarnyasg)
* [x] Add support for maps #67 (@jmarton)
* [ ] Add support for basic modifications (`CREATE`, `MERGE` and `DELETE`) #35 (@gkate90)
* [ ] Implement openCypher TCK tests #68 (@zsambek)

**Comment by szarnyasg** [comment]
See the `neo4j-reactive-driver` project in https://github.com/szarnyasg/neo4j-drivers.

**Comment by szarnyasg** [comment]
#68 is ongoing in https://github.com/bme-db-lab/opencypher-tck-tests (currently private).

**Comment by szarnyasg** [comment]
Closing this, follow the developments in #25 and #68.
